### ISSUE TITLE
Unit test refatoring

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-single-line-diagram#1]
* **Do you want to request a *feature* or report a *bug*?**
Design issue

* **What is the current behavior?**
Unit tests have been badly designed. It is not real "unit" test as most of them test the full diagram generation process. Consequently our unit test are hard to maintain and each time we change something in code, we need to regenerate SVG files. Worst, we most of the time regenerate reference SVG files without really looking at them.

* **What is the expected behavior?**
We need have real unit tests and not integration tests. I propose the following change.
   - In all different voltage level, substation tests (with small network specially designed for a specific purpose), we should not compare SVG anymore but only the data model (nodes + cells + blocks + coordinates x,y of nodes). We can do that by generating the data model json (here I'am talking about (XXX::writeJson methods, not metadata json!!!!!) and compare to a reference json. So with this change, most of the unit test won't depend anymore of CSS, component library, etc. (remark: it is very likely that the existing data model json export will have to be enriched).

  - The DefaultSVGWriter will be tested on the other side, by creating "by hand" a data model, affecting coordinates and generating a SVG, then comparing with a reference SVG. A few test data models will have to be design to test all the features of DefaultSVGWriter.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by FranckLecuyer** [comment]
For the second part of this issue :
> The DefaultSVGWriter will be tested on the other side, by creating "by hand" a data model, affecting 
> coordinates and generating a SVG, then comparing with a reference SVG. A few test data models will have to be design to test all the features of DefaultSVGWriter.

Can you be more explicit on "_creating by hand a data model_"

Does it signify that we have to construct this data model by reading a Json file, or that we create a network with voltagelevel, like we do in the different test cases ?

**Comment by geofjamg** [comment]
> For the second part of this issue :
> 
> > The DefaultSVGWriter will be tested on the other side, by creating "by hand" a data model, affecting
> > coordinates and generating a SVG, then comparing with a reference SVG. A few test data models will have to be design to test all the features of DefaultSVGWriter.
> 
> Can you be more explicit on "_creating by hand a data model_"
> 
> Does it signify that we have to construct this data model by reading a Json file like one generated in the first part, or that we create a network with substations, voltage levels, loads, generators, transformers ....,, like we do in the different test cases ?

The idea is when we test the SVG writing part to be independent of evolution in the layout part (to avoid impact on these unit tests). So I think it would be better for SVGWriter unit test to programmatically create a graph model (by adding nodes and  edges and set x,y, etc) and then generate a svg and then compare to a reference.

**Comment by geofjamg** [comment]
Solve in #41
