### ISSUE TITLE
Node decorators

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-single-line-diagram#15]
* **Do you want to request a *feature* or report a *bug*?**
Feature

It would be nice to be able to add custom SVG around node like labels (for instance to add a lock picture in case of line planned outage)

**Comment by cedrtheb** [comment]
Hello,
Maybe some pictures to illustrate ?
Regards,
Cédric.

**Comment by cedrtheb** [comment]
@geofjamg  Any news on this ?
What about the possibility to generalize it to any component?
Regards,
Cédric.
