### ISSUE TITLE
Provide example of diagram shown on the front page

### ISSUE THREAD

**Issue by bovium** [powsybl/powsybl-single-line-diagram#160]
* **Do you want to request a *feature* or report a *bug*?**
Documentation/Example

* **What is the current behavior?**
The is no example of how to create the layout shown on the front page.

It is not possible to create the diagram using the VoltageLevelDiagram as it only visualizes one VoltageLevel pr. diagram.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
It is not a bug, but merely lacking documentation on how to create the diagram shown on the front page.

* **What is the expected behavior?**
Better example on how to create the diagram shown on the front page.

* **What is the motivation / use case for changing the behavior?**
There should exist documentation on how to create the diagram illustrated on the front page.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.4.0
  - OS Version: Windows 64

**Comment by floriand-e2r** [comment]
Hi; I was wondering, are you interested mostly in creating the diagram by programmatically defining each of its components? or rather by importing a file corresponding to that diagram, a CGMES file for instance?
