### ISSUE TITLE
No space for arrows

### ISSUE THREAD

**Issue by floriand-e2r** [powsybl/powsybl-single-line-diagram#179]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
No extra space is left for displaying arrows: they are displayed between feeder and first node/equipment encountered, and often overlap/touch those if there is not enough place.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Display a voltage level with a feeder linked to a bus bar section with two consecutive switches or more, for instance [the example in README.md](https://github.com/powsybl/powsybl-single-line-diagram/raw/master/.github/diagram-demo.svg), where some arrows are below switches, or the following:
![arrowsTooClose3](https://user-images.githubusercontent.com/66690739/96572228-dfa9af00-12cc-11eb-90f3-23c1c4be5f8b.png) ![arrowsTooClose2](https://user-images.githubusercontent.com/66690739/96572229-e0424580-12cc-11eb-8db3-855b85861059.png) ![arrowsTooClose](https://user-images.githubusercontent.com/66690739/96572231-e0dadc00-12cc-11eb-8b18-4cc1a078c7a5.png)

* **What is the expected behavior?**
Some space between the arrows and the switch

* **What is the motivation / use case for changing the behavior?**
Better looking diagrams

**Comment by floriand-e2r** [comment]
In fact there's already code in `PositionVoltageLevelLayout` to free some space for arrows, but that code only shifts the feeders 20 pixels away for that (even if not needed). I can adapt the existing code for now, and maybe in the future we add a fictitious node to avoid possible side effects. What do you think @BenoitJeanson?

**Comment by BenoitJeanson** [comment]
I suggest to add a parameter in LayoutParameters like spaceForFeederArrows. Then, when we want to draw arrows, the calculation of the ExternCell should use (externCellHeight-minSpaceForFeederArrows) space for the nodes between the last node of the LegBlock (the one that is not stuck to the BusNode) and last node before Feeder… and yes sometime an extra ficticious node will be required.
By doing this, a side effect will be that all the arrows will all be aligned: but actually this should be pretty, and readable!
