### ISSUE TITLE
Font and background color configuration

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-single-line-diagram#21]
* **Do you want to request a *feature* or report a *bug*?**
A feature.

* **What is the current behavior?**
Font and background color is hard  coded.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

* **What is the expected behavior?**
To be able to configure background color (hex string) and font in ComponentLibrary using component.css

* **What is the motivation / use case for changing the behavior?**
To adapt font and background color to components style.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0-SNAPSHOT
  - OS Version: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by flo-dup** [comment]
Fonts are now in the CSS, but background color needs the viewbox (#87).
