### ISSUE TITLE
FeederPrimaryBlock is not Consistent

### ISSUE THREAD

**Issue by aybukeertekin** [powsybl/powsybl-single-line-diagram#221]
I am trying to draw single line diagram of a large cim file using single line diagram viewer. However, it says FeederPrimaryBlock is not consistent and does not draw some of the substations. Can you please explain what the reason can be?

  - PowSyBl Version: 3.8.0
  - OS Version: Windows 7

**Comment by floriand-e2r** [comment]
Hi, your issue looks very similar to a bug which was corrected on release 1.9.0 of powsybl-single-line-diagram (#208). Which version are you using? In fact we just released 2.0.0 today if you want to try it out!
If you're still experiencing the "non consistent" error with the 1.9.0 or 2.0.0 version, could you provide more details? cim extract of the substation ideally, or at least some traces?

**Comment by aybukeertekin** [comment]
Hi! I have updated powsybl-single-line-diagram and it solved my problem. Thank you!
