### ISSUE TITLE
Missing Initial Values for DanglingLine Component

### ISSUE THREAD

**Issue by yasstec** [powsybl/powsybl-single-line-diagram#29]
In the Default diagram value provider ("DefaultDiagramInitialValueProvider"), the get initial value method is missing values (P, Q...) for some components as "DanglingLine",  can you please set initial values for all components of the same node type (especially for FeederNode).

**Comment by FranckLecuyer** [comment]
Which values must we select for a dangling line in DefaultDiagramInitialValueProvider ?

P0, Q0 defined in DanglingLine interface (like for a load in the Load interface)
P, Q defined on the Terminal (like for a generator)

**Comment by geofjamg** [comment]
> Which values must we select for a dangling line in DefaultDiagramInitialValueProvider ?
> 
> P0, Q0 defined in DanglingLine interface (like for a load in the Load interface)
> P, Q defined on the Terminal (like for a generator)

Good point, what is done for loads is wrong we must use calculated flows so .getTerminal().getXXX.

**Comment by FranckLecuyer** [comment]
Ok. I will correct that also ...

**Comment by geofjamg** [comment]
Fixed by PR #30
