### ISSUE TITLE
Possibility to add indicators on busbarsection

### ISSUE THREAD

**Issue by cedrtheb** [powsybl/powsybl-single-line-diagram#311]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
See the attached picture:
![image](https://user-images.githubusercontent.com/47815381/145223679-92dad0f0-de6b-449b-85b2-d435ed77ff90.png)

We would like to add the voltage lack information on the bus bar section if available

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by flo-dup** [comment]
As the indicators are displayed on feeders thanks to `LabelProvider::getFeederInfos`, I think we should do something similar for the busbar sections, that is, creating a `BusbarInfo` class which will be used to draw/write information on the busbar, either on its left or on its right, and which is provided through the `LabelProvider`. The space reserved for that would be 0 px by default, but set throught `LayoutParameters`

**Comment by flo-dup** [comment]
I think the simpler way to do this would be to add a cell for it, but then we need to add a parameter in `PositionVoltageLevelLayoutFactory` to tell whether we want this or not. This argument needs to be passed on to the BlockPositionner::determineBlockPositions method, which will increase the hPos by 2 (a cell is 2 units wide) inside the loop for each subsections. This leads to these kind of diagrams:

![screenshot](https://user-images.githubusercontent.com/66690739/154934531-26a09f86-ebc1-4602-adcb-a463cb887eeb.png)
![screenshot](https://user-images.githubusercontent.com/66690739/154934568-8a3b0dd5-2d75-4e4b-a951-068789a02cb2.png)
