### ISSUE TITLE
Irrelevant use of suffix _ONE / _TWO for the lines which originates from bus

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/powsybl-single-line-diagram#393]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Suffix _ONE and _TWO are still used for the lines which are originating from bus

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Bug , difficult , but take a CGMES IEEE14 network, find the voltage level where lines originate from the bus and then look for the suffix _ONE 

* **What is the expected behavior?**
The lines should not have such suffixes for lines

* **What is the motivation / use case for changing the behavior?**
Clean irregularities

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
As discussed with @flo-dup, this could be fixed by just using the equipmentId instead of the ID to fill feeder label.

**Comment by AnkurArohi** [comment]
@geofjamg 
I am trying the same 
But here Line type has no equipmentId



................................

private void addLineEdges(Graph graph, List<Line> lines) {
    Set<String> linesIds = new HashSet<>();
    lines.forEach(line -> {
        if (!linesIds.contains(line.getId())) {
            Terminal t1 = line.getTerminal1();
            Terminal t2 = line.getTerminal2();

            VoltageLevel vl1 = t1.getVoltageLevel();
            VoltageLevel vl2 = t2.getVoltageLevel();

            VoltageLevelGraph g1 = graph.getVoltageLevel(vl1.getId());
            VoltageLevelGraph g2 = graph.getVoltageLevel(vl2.getId());

            Node n1 = g1.getNode(line.getId() + "_" + line.getSide(t1).name());
            Node n2 = g2.getNode(line.getId() + "_" + line.getSide(t2).name());
            graph.addLineEdge(line.getId(), n1, n2);
            linesIds.add(line.getId());
        }
    });
}

**Comment by flo-dup** [comment]
You were referencing some code coming from building the graph, but the problem's not there: it's just a matter of choosing the proper label to display on the feeder node as said above. So it's later when generating the SVG with the DiagramLabelProvider. You should have a look at what String is taken, and correct it.

(Note that I updated your comment with code reference, as it was not clear that you were referencing some existing code)
