### ISSUE TITLE
Graphical issues in voltage level

### ISSUE THREAD

**Issue by cedrtheb** [powsybl/powsybl-single-line-diagram#4]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Condo symbol not touching the line if in top position (MEZE5P7):  
![CondoNotInTouch](https://user-images.githubusercontent.com/47815381/66496929-fdd6af80-eabb-11e9-9b91-f3d0f604947b.jpg)  
Lines over breakers (ALL):    
![linesOverBreakers](https://user-images.githubusercontent.com/47815381/66496930-fe6f4600-eabb-11e9-8065-819ea58c1646.jpg)
Disconnector shape "\\" instead of "/" (MEZE5P7 or .CTLHP3):  
![wrongOrientation](https://user-images.githubusercontent.com/47815381/66496931-fe6f4600-eabb-11e9-99e6-100e7913f9ac.jpg)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
@cedrtheb could you check the 3 bugs have been fixed now?
