### ISSUE TITLE
NominalVoltageDiagramStyleProvider regression

### ISSUE THREAD

**Issue by quinarygio** [powsybl/powsybl-single-line-diagram#47]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
NominalVoltageDiagramStyleProvider does not apply any style to wires and arrows are not displayed correctly when wire is connected to a  two windings transformer.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Choose nominal voltage as style provider:

![image](https://user-images.githubusercontent.com/19426449/68109976-349dbb00-feec-11e9-8751-54597f4411cd.png)

* **What is the expected behavior?**

Wires should be colored according to the nominal voltage.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Fixed by #55
