### ISSUE TITLE
Weird grid display behaviour (layouts other than "Auto*")

### ISSUE THREAD

**Issue by CBiasuzzi** [powsybl/powsybl-single-line-diagram#48]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**

The grid is not displayed correctly, using layouts other than Auto* e.g.   Random, CGMES.
Apparently, the data needed to create the grid, in the SVG writer, is missing or incorrectly set.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

To illustrate the problem, here below are three screenshots taken from the substation viewer (CGMES network "MiniGrid", NodeBreaker version, selected substation is "Sub4"; network found in powsybl-core's cgmes/cgmes-conformity module). 
Note the grid(s) rendered as a couple of small dotted boxes, for the Random and the CGMES layouts (first two pictures) WRT the Auto-without-extensions/Horizontal layout, used in the third image.

**Random layout**
![random](https://user-images.githubusercontent.com/17046470/68250418-2e5d2b00-0021-11ea-905c-1cb5d6dd1fe1.png)

**CGMES layout**
![cgmes_grid](https://user-images.githubusercontent.com/17046470/68250436-34530c00-0021-11ea-873d-3d9f1e64d9a7.png)

**Auto-without-extensions layout**
![auto](https://user-images.githubusercontent.com/17046470/68250446-3cab4700-0021-11ea-991c-1bdcad7f6090.png)

* **What is the expected behavior?**
the meaning of the expected grid (assuming the "Auto" is the correct rendering)  should be better clarified: the meaning of the vertical lines (feeder separator?) and the horizontal lines; also, why a separate grid for each voltage level diagram?

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
As grid is closely linked to automatic layout data intermediate position, we should detect that there is no position set in the data model and not display the grid.
