### ISSUE TITLE
viewer : multiple layouts panel to compare effects of parameters

### ISSUE THREAD

**Issue by BenoitJeanson** [powsybl/powsybl-single-line-diagram#57]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
The viewer allows to show one diagram with the set of paramers on the right side.

* **What is the expected behavior?**
Having the possibility of displaying the same diagram with different (2 would be probably already enough) sets of parameters.
One option would be to duplicate into tabs the panel with the layout and parameters.
More usefull would be to split the screen (vertically as the interesting substation layouts are horizontal) and in the configuration panel having the opportunity to switch between the different configurations

* **What is the motivation / use case for changing the behavior?**
testing the rendering with different PositionFinder

**Comment by flo-dup** [comment]
Viewer has been moved to powsybl-dev-tools, so the issue has been copied there
