### ISSUE TITLE
Issue with wires connected to feeders

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-single-line-diagram#69]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Sometime wires directly connected to a feeder do not start in the right direction. In the following example, all top line feeders start from the left and then go down:

![image](https://user-images.githubusercontent.com/632675/69534944-166f2c00-0f7b-11ea-9b1d-70d6a4b21c99.png)

* **What is the expected behavior?**
It would be prettier to go straight down.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by FranckLecuyer** [comment]
I think that the problem is caused by a line feeder, which has no SVG component associated in the SVG components library (and then if affects the search of better anchor points to draw the edge)
Maybe the best way to solve that, is to associate an svg component with a line feeder, and make it invisible ...

**Comment by geofjamg** [comment]
> I think that the problem is caused by a line feeder, which has no SVG component associated in the SVG components library (and then if affects the search of better anchor points to draw the edge)
> Maybe the best way to solve that, is to associate an svg component with a line feeder, and make it invisible : I just have tried that and it seems successful ....

Is it really linked to the fact there is no SVG, or just no anchor points defined?

**Comment by FranckLecuyer** [comment]
It is linked to the fact that there are no anchor points defined
So, we can just add a description for a LINE component in components.xml, with a size and one anchor point, but with no svg subComponent part : It also seems to be ok

**Comment by geofjamg** [comment]
Fixed in #72
